<a href="https://colab.research.google.com/github/vamsivirigineni/Python-Data-Analysis/blob/main/NumPy/NumPy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy Practice Worksheet Solutions

In [ ]:
import numpy as np

### 1. Creating Arrays

In [ ]:
# 1. Create a NumPy array from the list: [12, 15, 18, 21, 24].
arr1 = np.array([12, 15, 18, 21, 24])
arr1

array([12, 15, 18, 21, 24])

In [ ]:
# 2. Create an array from 10 to 50 with a step size of 5.
arr2 = np.arange(10, 51, 5) # 51 because arange excludes the stop value
arr2

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
# 3. Create 8 equally spaced values between 20 and 60.
arr3 = np.linspace(20, 60, 8)
arr3

array([20.        , 25.71428571, 31.42857143, 37.14285714, 42.85714286,
       48.57142857, 54.28571429, 60.        ])

In [ ]:
# 4. Create a 3x3 array of zeros and a 2x5 array of ones.
zeros_array = np.zeros((3, 3))
ones_array = np.ones((2, 5))
zeros_array
ones_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# 5. Create a 4x4 identity matrix and an array of 6 random integers between 50 and 100.
identity_matrix = np.eye(4)
random_integers = np.random.randint(50, 101, 6) # 101 because randint excludes the high value
identity_matrix
random_integers

array([81, 86, 87, 55, 87, 74])

### 2. Random Array Generation

In [ ]:
# 1. Generate 10 random decimal numbers between 0 and 1.
dec = np.random.rand(10)
dec

array([0.05486256, 0.83973068, 0.17364974, 0.79071901, 0.1055387 ,
       0.78270716, 0.65968222, 0.95143056, 0.31050599, 0.85920351])

In [ ]:
# 2. Generate a 3x4 array of random numbers between 0 and 1.
arr = np.random.rand(3, 4)
arr

array([[0.57626597, 0.27966456, 0.76834416, 0.89692281],
       [0.11185158, 0.46517446, 0.88430489, 0.2266269 ],
       [0.26476582, 0.96100438, 0.7609401 , 0.12220087]])

In [ ]:
# 3. Generate 8 random integers between 10 and 30.
arr3  = np.random.randint(10, 31, 8)
arr3

array([25, 19, 17, 24, 29, 17, 29, 26])

In [ ]:
# 4. Generate a 2x3 array of random numbers from the normal distribution.
arr4 = np.random.randn(2, 3)
arr4

array([[ 0.00357422, -0.73453393,  0.69843869],
       [-0.40133069,  0.49036732,  0.42130136]])

In [ ]:
# 5. Identify the appropriate NumPy method for: (a) Random integers (b) Random decimal numbers.
print("5. (a) Random integers: np.random.randint()")
print("   (b) Random decimal numbers: np.random.rand() (for uniform distribution between 0 and 1) or np.random.normal() (for normal distribution)")

5. (a) Random integers: np.random.randint()
   (b) Random decimal numbers: np.random.rand() (for uniform distribution between 0 and 1) or np.random.normal() (for normal distribution)


### 3. Operator Precedence

In [ ]:
# 1. Predict the output: arr=np.array([10,20,30]); arr+5*2
# Prediction: Multiplication (5*2=10) first, then addition (arr+10). [20, 30, 40]
arr = np.array([10, 20, 30])
arr + 5 * 2

array([20, 30, 40])

In [ ]:
# 2. Predict the output: arr=np.array([5,10,15]); (arr+5)*2
# Prediction: Parentheses first (arr+5) = [10, 15, 20], then multiplication (*2) = [20, 30, 40]
arr = np.array([5, 10, 15])
(arr + 5) * 2

array([20, 30, 40])

In [ ]:
# 3. Predict the output: arr=np.array([4,8,12]); arr/2+3
# Prediction: Division (arr/2) = [2, 4, 6], then addition (+3) = [5, 7, 9]
arr = np.array([4, 8, 12])
arr / 2 + 3

array([5., 7., 9.])

In [ ]:
# 4. Predict the output: arr=np.array([2,4,6]); arr*3-2
# Prediction: Multiplication (arr*3) = [6, 12, 18], then subtraction (-2) = [4, 10, 16]
arr = np.array([2, 4, 6])
arr * 3 - 2

array([ 4, 10, 16])

In [ ]:
# 5. Predict the output: arr=np.array([5,10,15]); arr+10/2
# Prediction: Division (10/2=5) first, then addition (arr+5) = [10, 15, 20]
arr = np.array([5, 10, 15])
arr + 10 / 2

array([10., 15., 20.])

### 4. 1D Array Indexing

In [ ]:
arr = np.array([12, 25, 37, 48, 59, 63, 75])

# 1. Access the first element.
arr[0]

np.int64(12)

In [ ]:
# 2. Access the last element.
arr[-1]

np.int64(75)

In [ ]:
# 3. Access the fourth element.
arr[3]

np.int64(48)

In [ ]:
# 4. Access the second last element.
arr[-2]

np.int64(63)

In [ ]:
# 5. Access the value 59.
arr[4]


np.int64(59)

### 5. 1D Array Slicing

In [ ]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# 1. Extract the first five elements.
arr[:5]

array([ 5, 10, 15, 20, 25])

In [ ]:
# 2. Extract the last four elements.
arr[-4:]

array([35, 40, 45, 50])

In [ ]:
# 3. Extract every second element.
arr[::2]

array([ 5, 15, 25, 35, 45])

In [ ]:
# 4. Extract elements from index 3 to index 7.
arr[3:8] # Index 7 is exclusive in slicing

array([20, 25, 30, 35, 40])

In [ ]:
# 5. Reverse the array.
arr[::-1]

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

### 6. Array and Constant Operations

In [ ]:
arr = np.array([10, 20, 30, 40])

# 1. Add 100 to every element.
arr + 100

array([110, 120, 130, 140])

In [ ]:
# 2. Subtract 5 from every element.
arr - 5

array([ 5, 15, 25, 35])

In [ ]:
# 3. Multiply every element by 3.
arr * 3

array([ 30,  60,  90, 120])

In [ ]:
# 4. Divide every element by 2.
arr / 2

array([ 5., 10., 15., 20.])

In [ ]:
# 5. Find the square of every element.
arr ** 2

array([ 100,  400,  900, 1600])

### 7. Array-to-Array Operations

In [ ]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])

# 1. Perform addition.
a + b

array([ 3,  7, 11, 15])

In [ ]:
# 2. Subtract b from a.
 a - b

2. Subtraction (a - b): [1 1 1 1]


In [ ]:
# 3. Multiply the arrays.
a * b

array([ 2, 12, 30, 56])

In [ ]:
# 4. Divide a by b.
a / b

array([2.        , 1.33333333, 1.2       , 1.14285714])

In [ ]:
# 5. Find the remainder when a is divided by b.
a % b

array([0, 1, 1, 1])

### 8. Statistical Operations (1D)

In [ ]:
arr = np.array([12, 15, 18, 21, 24, 27])

# 1. Find the sum.\
np.sum(arr)

np.int64(117)

In [ ]:
# 2. Find the mean.
np.mean(arr)

np.float64(19.5)

In [ ]:
# 3. Find the median.
np.median(arr)

3. Median: 19.5


In [ ]:
# 4. Find the maximum value.
np.max(arr)

4. Maximum value: 27


In [ ]:
# 5. Find the minimum value.
np.min(arr)

np.int64(12)

### 9. 2D Array Indexing

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original 2D Array:\n", arr)

# 1. Access 50.
arr[1, 1]

Original 2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


np.int64(50)

In [ ]:
# 2. Access 30.
arr[0, 2]

2. Access 30: 30


In [ ]:
# 3. Access 70.
arr[2, 0]

3. Access 70: 70


In [ ]:
# 4. Access the element at row 2 column 3 (using 0-based indexing: row 1, column 2).
arr[1, 2]

np.int64(60)

In [ ]:
# 5. Access the last element.
arr[-1, -1]

np.int64(90)

### 10. 2D Array Slicing

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr

# 1. Extract the first row.
arr[0, :]

array([10, 20, 30])

In [ ]:
# 2. Extract the second column.
arr[:, 1]

2. Second column: [20 50 80]


In [ ]:
# 3. Extract the last two rows.
arr[-2:, :]

array([[40, 50, 60],
       [70, 80, 90]])

In [ ]:
# 4. Extract [[40,50],[70,80]].
arr[1:, :2]

array([[40, 50],
       [70, 80]])

In [ ]:
# 5. Extract the last column.
arr[:, -1]

array([30, 60, 90])

### 11. Operations on 2D Arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

# 1. Add 10 to every element.
arr + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
# 2. Multiply every element by 5.
arr * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
# 3. Find the square of every element.
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
# 4. Subtract 2 from every element.
arr - 2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [ ]:
# 5. Divide every element by 2.
arr / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

### 12. Statistical Operations (2D)

In [ ]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
arr

# 1. Find the total sum.
np.sum(arr)

np.int64(210)

In [ ]:
# 2. Find the mean of all elements.
np.mean(arr)

2. Mean of all elements: 35.0


In [ ]:
# 3. Find the median.
# For 2D array, median flattens by default, or specify axis=None
np.median(arr)

3. Median of all elements: 35.0


In [ ]:
# 4. Find the sum of each row.
np.sum(arr, axis=1)

4. Sum of each row: [ 60 150]


In [ ]:
# 5. Find the sum of each column.
np.sum(arr, axis=0)

5. Sum of each column: [50 70 90]


### 13. Shape, Reshape and Flatten

In [ ]:
# 1. Convert arr=np.arange(12) into a 3x4 array.
arr_12 = np.arange(12)
arr = arr_12.reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 2. Given arr=np.arange(16).reshape(4,4), find its shape.
arr_1 = np.arange(16).reshape(4, 4)
arr_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# 3. Reshape arr=np.arange(24) into 2x3x4.
arr_24 = np.arange(24)
reshaped = arr_24.reshape(2, 3, 4)
reshaped

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# 4. Flatten arr=np.array([[10,20],[30,40]]). Using .flatten()
arr_2d = np.array([[10, 20], [30, 40]])
flattened_arr = arr_2d.flatten()
flattened_arr

array([10, 20, 30, 40])

In [ ]:
# 5. For arr=np.arange(15), find ndim, shape and size.
arr_15 = np.arange(15)
print("5. Array:", arr_15)
print("   ndim:", arr_15.ndim)
print("   shape:", arr_15.shape)
print("   size:", arr_15.size)

5. Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
   ndim: 1
   shape: (15,)
   size: 15


### 14. Integrated Practice

In [ ]:
# 1. Create a 5x5 identity matrix and multiply every element by 10.
identity_5x5 = np.eye(5)
multiplied_identity = identity_5x5 * 10
multiplied_identity

array([[10.,  0.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0.,  0., 10.,  0.],
       [ 0.,  0.,  0.,  0., 10.]])

In [ ]:
# 2. Create an array from 1 to 50 and find the sum, mean and median.
arr_1_50 = np.arange(1, 51) # Includes 50
print("2. Array from 1 to 50:", arr_1_50)
print("   Sum:", np.sum(arr_1_50))
print("   Mean:", np.mean(arr_1_50))
print("   Median:", np.median(arr_1_50))

2. Array from 1 to 50: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
   Sum: 1275
   Mean: 25.5
   Median: 25.5


In [ ]:
# 3. Generate a 4x4 random integer array between 1 and 100. Find the maximum, minimum and mean.
rand_int_4x4 = np.random.randint(1, 101, size=(4, 4))
print("3. 4x4 Random integer array (1-100):\n", rand_int_4x4)
print("   Maximum:", np.max(rand_int_4x4))
print("   Minimum:", np.min(rand_int_4x4))
print("   Mean:", np.mean(rand_int_4x4))

3. 4x4 Random integer array (1-100):
 [[40 33 33 44]
 [37 60 50 43]
 [85 16 25  3]
 [25 13 52 32]]
   Maximum: 85
   Minimum: 3
   Mean: 36.9375


In [ ]:
# 4. Convert [2,4,6,8,10,12,14,16,18] into a NumPy array and reshape it into a 3x3 matrix.
list_data = [2, 4, 6, 8, 10, 12, 14, 16, 18]
numpy_arr_from_list = np.array(list_data)
reshaped_3x3 = numpy_arr_from_list.reshape(3, 3)
print("4. Reshaped 3x3 matrix from list:\n", reshaped_3x3)

4. Reshaped 3x3 matrix from list:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
# 5. Mini Project: A company stores the weekly sales of five employees:
sales = [25000, 32000, 28000, 35000, 30000]

# 1. Convert the list into a NumPy array.
sales_array = np.array(sales)
print("5. Mini Project:")
print("   1. Sales as NumPy array:", sales_array)

# 2. Find the total sales.
total_sales = np.sum(sales_array)
print("   2. Total sales:", total_sales)

# 3. Find the average sales.
average_sales = np.mean(sales_array)
print("   3. Average sales:", average_sales)

# 4. Add a £2,000 bonus to every employee.
bonus_sales = sales_array + 2000
print("   4. Sales with £2,000 bonus:", bonus_sales)

# 5. Find the highest and lowest sales.
highest_sales = np.max(sales_array)
lowest_sales = np.min(sales_array)
print("   5. Highest sales:", highest_sales)
print("      Lowest sales:", lowest_sales)

# 6. Display the updated sales array (with bonus).
print("   6. Updated sales array (with bonus):", bonus_sales)

5. Mini Project:
   1. Sales as NumPy array: [25000 32000 28000 35000 30000]
   2. Total sales: 150000
   3. Average sales: 30000.0
   4. Sales with £2,000 bonus: [27000 34000 30000 37000 32000]
   5. Highest sales: 35000
      Lowest sales: 25000
   6. Updated sales array (with bonus): [27000 34000 30000 37000 32000]
