<a href="https://colab.research.google.com/github/vamsivirigineni/Python-Data-Analysis/blob/main/NumPy/NumPy_Test_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:

#1.create a 5 × 5 NumPy array of random integers between 1 and 100. Find the maximum value.


In [ ]:
a = np.random.randint(1, 101, (5, 5))
print(a)

print("Maximum:", np.max(a))

[[69 61 97 27 57]
 [95 49 40 11 87]
 [61 25 39 46 43]
 [52 52 58 91 98]
 [32 10 71 44 40]]
Maximum: 98


In [ ]:
#2.Create a 4 × 6 array of random integers between 10 and 100. Find the minimum value in each row.

In [ ]:
a = np.random.randint(10,101,(4,6))
print(a)
print("minimun:",np.min(a))

[[ 44  61  83  77  58  72]
 [ 99  79  14  28  23  94]
 [ 67  11  10  32  13  85]
 [ 30 100  50  34  43  32]]
minimun: 10


3.Generate 20 random integers between 1 and 50. Find all values that are greater than the mean.

In [ ]:
a = np.random.randint(1,51,20)
print(a)
print("Mean:",np.mean(a))
print("Greater than mean:",a[a>np.mean(a)])

[21 22 28 42 37 21 28 13 48 29  6  1 10 26 21  8 10 49 25 27]
Mean: 23.6
Greater than mean: [28 42 37 28 48 29 26 49 25 27]


4.Create a 5 × 5 random array between 1 and 100. Replace every value less than 50 with 0.

In [ ]:
a = np.random.randint(1,101,(5,5))
print(a)
print("Replace:",np.where(a<50,0,a))

[[ 75  96  50  25  62]
 [ 24   9  61  91 100]
 [ 73  75  10  65  20]
 [ 93  67  38  65  21]
 [  6  89  11  17  27]]
Replace: [[ 75  96  50   0  62]
 [  0   0  61  91 100]
 [ 73  75   0  65   0]
 [ 93  67   0  65   0]
 [  0  89   0   0   0]]


5.Generate a 3 × 4 array of random integers between 1 and 50. Calculate the sum of each row and each column.

In [ ]:
a = np.random.randint(1,51,(3,4))
print(a)
print("Sum of each row:",np.sum(a,axis=1))
print("Sum of each column:",np.sum(a,axis=0))

[[ 5 26 25 20]
 [ 6 49 10 34]
 [46 19 47 36]]
Sum of each row: [ 76  99 148]
Sum of each column: [57 94 82 90]



6.Create a 4 × 4 matrix of random integers between 1 and 20. Find the maximum value in each column and its corresponding index.

In [ ]:
a = np.random.randint(1,21,(4,4))
print(a)
print("maximum value in column",np.max(a,axis=0))
print("index of maximum value in column",np.argmax(a,axis=0))

[[16  2 12  8]
 [ 5 13  4  8]
 [20 14 10 12]
 [11 20 11 10]]
maximum value in column [20 20 12 12]
index of maximum value in column [2 3 0 2]


7.Generate 15 random integers between 1 and 100. Sort them in ascending and descending order.


In [ ]:
a = np.random.randint(1,101,15)
print(a)
print("Ascending order:",np.sort(a))
print("Descending order:",np.sort(a)[::-1])

[ 77  45  97  71  11  55  88  67  13  25  28 100   3  46  64]
Ascending order: [  3  11  13  25  28  45  46  55  64  67  71  77  88  97 100]
Descending order: [100  97  88  77  71  67  64  55  46  45  28  25  13  11   3]


8.Create a 5 × 5 matrix of random integers. Extract the main diagonal and calculate its sum.

In [ ]:
a = np.random.randint(1,101,(5,5))
print(a)
diagonal = np.diag(a)
print("diagonal values",diagonal)
print("sum of diagonal values",sum(diagonal))

[[41 41 31 19 15]
 [20 53 18 79 10]
 [65 23 81  5 33]
 [56 74 36 59 50]
 [15 21 24 32 88]]
diagonal values [41 53 81 59 88]
sum of diagonal values 322


9.Generate a 4 × 4 matrix and replace all even numbers with 0 while keeping odd numbers unchanged.

In [ ]:
a = np.random.randint(1,101,(4,4))
print(a)
print("Replace:",np.where(a%2 == 0,0,a))

[[17 47 95 28]
 [32 34 27 14]
 [61 34 63 13]
 [31 47  3 61]]
Replace: [[17 47 95  0]
 [ 0  0 27  0]
 [61  0 63 13]
 [31 47  3 61]]


10.Create a 6 × 6 random matrix. Find how many values are greater than 50, less than 50, and equal to 50.

In [ ]:
a = np.random.randint(1, 101, (6, 6))
print(a)

print("Greater than 50:", np.sum(a > 50))
print("Less than 50:", np.sum(a < 50))
print("Equal to 50:", np.sum(a == 50))

[[ 90   4  81  80  40  38]
 [  9  83  69   9 100  78]
 [ 63  50   8   5  61  80]
 [ 28  34  35  30  15  91]
 [ 16  54  49   3  97  65]
 [ 71  39  17  51  88  24]]
Greater than 50: 17
Less than 50: 18
Equal to 50: 1


11.Generate 10 random integers between 1 and 100. Find the top 3 largest values without using Python's built-in sorted().


In [ ]:
a = np.random.randint(1, 101)
print(a)
print(np.sorted(a)[-3:])

47


AttributeError: module 'numpy' has no attribute 'sorted'

12.Create a 3 × 5 matrix containing random integers. Find the row having the highest sum.

In [ ]:
a = np.random.randint(1,101,(3,5))
print(a)
add = np.sum(a,axis=1)
print("Row having the highest sum:",np.argmax(add))

[[ 21  65  69  13  61]
 [ 38  46  68  30  51]
 [ 78 100  34  51  57]]
Row having the highest sum: 2


13.Generate two 3 × 3 matrices containing random integers between 1 and 10. Perform element-wise addition, subtraction and multiplication.

In [ ]:
a = np.random.randint(1,11,(3,3))
b= np.random.randint(1,11,(3,3))
print(a)
print(b)
print("element-wise addition:",a+b)
print("element-wise sub:",a-b)
print("element-wise mul:",a*b)


[[2 6 5]
 [1 4 5]
 [1 9 8]]
[[ 7  8  6]
 [ 8  7  3]
 [ 8 10  4]]
element-wise addition: [[ 9 14 11]
 [ 9 11  8]
 [ 9 19 12]]
element-wise sub: [[-5 -2 -1]
 [-7 -3  2]
 [-7 -1  4]]
element-wise mul: [[14 48 30]
 [ 8 28 15]
 [ 8 90 32]]


14.Create a 3 × 4 matrix and use broadcasting to add [10, 20, 30, 40] to every row.



In [ ]:
a = np.random.randint(1,101,(3,4))
print(a)
b = np.array([10,20,30,40])
print(a+b)

[[67 38 67 20]
 [98 46 24 13]
 [26  7 77 96]]
[[ 77  58  97  60]
 [108  66  54  53]
 [ 36  27 107 136]]


15.Generate a 5 × 5 matrix of random integers. Normalize all values using:
(x - min) / (max - min)

In [ ]:
a = np.random.randint(1,101,(5,5))
print(a)
min = np.min(a)
max = np.max(a)
print((a-min)/(max-min))

[[11 79 24 34 92]
 [61 73 80 65 93]
 [89 28 93 46 19]
 [73 47 16 50 95]
 [73 20 13 83 93]]
[[0.         0.80952381 0.1547619  0.27380952 0.96428571]
 [0.5952381  0.73809524 0.82142857 0.64285714 0.97619048]
 [0.92857143 0.20238095 0.97619048 0.41666667 0.0952381 ]
 [0.73809524 0.42857143 0.05952381 0.46428571 1.        ]
 [0.73809524 0.10714286 0.02380952 0.85714286 0.97619048]]


16.Create an array of 20 random integers between 1 and 100. Replace values:
< 30 → 0
30–70 → 1
">70 → 2

In [ ]:
a= np.random.randint(1,101,20)
print(a)
print(np.where(a<30,0,np.where(a<70,1,2)))

[49 93 30 29  4 94 24 50 72 99 41 76 95 57 59 28  9 22 53  5]
[1 2 1 0 0 2 0 1 2 2 1 2 2 1 1 0 0 0 1 0]


17.Generate a 4 × 5 matrix of random integers. Find the second-largest value in the entire matrix.



In [ ]:
a = np.random.randint(1,101,(4,5))
print(a)
b = np.sort(a.flatten())
print(b)
print("Second largest value:",b[-2])


[[53 91 27 40 53]
 [63 55 57 64 76]
 [99 61 96 65 80]
 [82 70 46 31 62]]
[27 31 40 46 53 53 55 57 61 62 63 64 65 70 76 80 82 91 96 99]
Second largest value: 96


18.Create a 5 × 5 matrix and find all the values that occur more than once.



In [ ]:
a = np.random.randint(1, 11, (5, 5))
print(a)
print(np.unique(a[a>1]))

[[ 9  8  6  7  3]
 [ 6  9  5  8 10]
 [ 9  9  1  9  4]
 [10  1  8  7  3]
 [ 8  6  1  1  5]]
[ 3  4  5  6  7  8  9 10]


19.Generate 10 random integers between 1 and 100. Find the indices of all values greater than the average.


In [ ]:
a = np.random.randint(1,101,10)
print(a)
print("Average:",np.mean(a))
print("Indices of all values greater than the average:",np.where(a>np.mean(a)))

[74 24 81 76 40  4 81 80 50 99]
Average: 60.9
Indices of all values greater than the average: (array([0, 2, 3, 6, 7, 9]),)


20.Create a 4 × 4 matrix and calculate the sum of the main diagonal and anti-diagonal.


In [ ]:
a = np.random.randint(1,101,(4,4))
print(a)
# print("Sum of the main diagonal:",np.trace(a))
# print("Sum of the anti-diagonal:",np.trace(np.fliplr(a)))
dia = np.diag(a)
print(dia)
print("sum of main diagonla is :",sum(dia))


[[59 67 64  8]
 [64 65 92 47]
 [88 79 26 84]
 [41 31 76 30]]
[59 65 26 30]
sum of main diagonla is : 180


21.Generate a 3 × 6 matrix of random integers. Reshape it into a 2 × 9 matrix, then find its maximum and minimum values.


In [ ]:
a = np.random.randint(1,101,(3,6))
print(a)
print("Reshape:",a.reshape(2,9))
print("Maximum value:",np.max(a))
print("Minimum value:",np.min(a))


[[67 32 56 82 68 79]
 [71 55 20 34 17 30]
 [13  1 97  5 68 25]]
Reshape: [[67 32 56 82 68 79 71 55 20]
 [34 17 30 13  1 97  5 68 25]]
Maximum value: 97
Minimum value: 1


22.Create a 5 × 5 random matrix. Find the row and column position of the largest element using NumPy.


In [ ]:
a= np.random.randint(1,101,(5,5))
print(a)
print("Row position of the largest element:",np.argmax(a,axis=1))
print("Column position of the largest element:",np.argmax(a,axis=0))

[[ 27  47  78 100  60]
 [ 68  73  87  73  71]
 [ 52  60  52  37  18]
 [ 75  73  57  55  63]
 [ 79  78  28  90  88]]
Row position of the largest element: [3 2 1 0 3]
Column position of the largest element: [4 4 1 0 4]


23.Generate 10 random integers between 1 and 50. Create a new array containing only the unique values, then sort them.


In [ ]:
a = np.random.randint(1,51,10)
print(a)
b = np.unique(a)
print(b)
print(np.sort(b))

[27 44 12 24 25 41 12 13 21 13]
[12 13 21 24 25 27 41 44]
[12 13 21 24 25 27 41 44]


24.Create two arrays:
a = np.array([10, 20, 30, 40, 50])
b = np.array([15, 18, 35, 25, 60])
Find which positions have values where a is greater than b, and display those positions and values.

In [ ]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([15, 18, 35, 25, 60])
print(np.where(a>b))

(array([1, 3]),)


25.Generate a 5 × 5 matrix of random integers between 1 and 100. Find:
1.Maximum value
2.Minimum value
3.Mean
4.Standard deviation
5.Index of maximum value
6.Index of minimum value
7.Number of values greater than the mean

In [ ]:
a = np.random.randint(1,101,(5,5))
print(a)
print("Maximum value:",np.max(a))
print("Minimum value:",np.min(a))
print("Mean:",np.mean(a))
print("Standard deviation:",np.std(a))
print("Index of maximum value:",np.argmax(a))
print("Index of minimum value:",np.argmin(a))
print("Number of values greater than the mean:",np.sum(a>np.mean(a)))

[[66 50  8 51 41]
 [27 40 26 16  8]
 [34 59 24 74 96]
 [73 54 58 90 11]
 [71 19 64 88 46]]
Maximum value: 96
Minimum value: 8
Mean: 47.76
Standard deviation: 25.763974848613714
Index of maximum value: 14
Index of minimum value: 2
Number of values greater than the mean: 13
